version: '3.9'

services:
  api:
    build: ./api/
    hostname: api
    environment:
      - API_PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_ADMIN_USER}
      - POSTGRES_PASSWORD=${DB_ADMIN_PASS}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./api/code:/app/
    working_dir: /app/
    ports:
      - "${API_PORT}:${API_PORT}"
      
  consumer:
    build:  ./consumer/
    hostname: consumer
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - CONSUMER_PORT=${CONSUMER_PORT}
    volumes:
      - ./consumer/code:/app/
    ports:
      - "${CONSUMER_PORT}:${CONSUMER_PORT}"

  db_admin: 
    image: dpage/pgadmin4
    hostname: dba # optional
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGA_ADMIN_NAME}
      - PGADMIN_DEFAULT_PASSWORD=${PGA_ADMIN_PASS}
    ports:
      - "${PGA_PORT}:${PGA_PORT}"

  db:
    image: postgres:12.12
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=${DB_ADMIN_USER}
      - POSTGRES_PASSWORD=${DB_ADMIN_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes: 
      - ./db/data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
